FROM python:3.11-alpine

# RUN apt-get update \
# 	&& apt-get install -y dos2unix \
# 	&& rm -rf /var/lib/apt/lists/* /var/cache/apt/*

# # pip19.0.1 与 pyinstaller3.4 不兼容，需要降级安装
# RUN pip install --no-cache-dir pip==18.1 \
# 	&& pip install --no-cache-dir pyinstaller==3.4

# RUN pip install --no-cache-dir --upgrade pip \
# 	&& pip install --no-cache-dir --upgrade setuptools

# RUN echo "export PS1='[\A \u@\H \w]\\$ '" >> $HOME/.bashrc \
# 	&& echo "alias ll='ls -lh --color'" >> $HOME/.bashrc

CMD ["/bin/sh"]