version: "3.7"
services:
  python_base:
    pull_policy: never
    image: cuile/${IMAGE}_base
    container_name: python_base
    build:
      context: ${PROXY}https://github.com/Cuile/Docker-Image.git#:Python/base/docker
      args:
        - IMAGE=${IMAGE}
  mobile_number_generator:
    pull_policy: never
    image: cuile/mobile_number_generator
    container_name: mobile_number_generator
    build: 
      context: ${PROXY}https://github.com/Cuile/Docker-Image.git#:Python/Dev/docker
      args:
        - IMAGE=${IMAGE}
    volumes:
      - ../src:/usr/app/src/:ro
      - ../data:/usr/app/data/:rw
      - ../bin:/usr/app/bin/:rw
      - ../build:/usr/app/build/:rw
    depends_on:
      - python_base
