version: "3.7"
services:
  mobile_number_generator:
    image: mobile_number_generator
    container_name: mobile_number_generator
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../src:/root/src/:ro
      - ../data:/root/data/:rw
    working_dir:  /root/
    tty: true
