version: "3.7"
services:
  mobile_number_generator:
    image: mobile_number_generator:1
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - ../src:/root/src/:ro
      - ../data:/root/data/:rw
    working_dir:  /root/
    tty: true
