version: "3.7"
services:
  mobile_number_generator:
    image: mobile_number_generator
    container_name: mobile_number_generator
    build: ${PROXY}https://github.com/Cuile/Docker-Image.git#:Python/base/docker
    volumes:
      - ../src:/root/src/:ro
      - ../data:/root/data/:rw
      - ../bin:/root/bin/:rw
      - ../build:/root/build/:rw
    working_dir:  /root/src/
