version: "3.7"
services:
  python_base:
    image: cuile/python:base
    build:
      context: ${PROXY}https://github.com/Cuile/Docker-Image.git#:Python/base/docker
      args:
        - IMAGE=${IMAGE}
  mobile_number_generator:
    image: cuile/mobile_number_generator
    build: 
      context: ${PROXY}https://github.com/Cuile/Docker-Image.git#:Python/Dev/docker
      args:
        - IMAGE=${IMAGE}
    volumes:
      - ../src:/usr/app/src/:ro
      - ../data:/usr/app/data/:rw
      - ../bin:/usr/app/bin/:rw
      - ../build:/usr/app/build/:rw
