version: "3.7"
services:
  mobile_number_generator:
    image: cuile/mobile_number_generator
    container_name: culie/mobile_number_generator
    build: 
      context: ${PROXY}https://github.com/Cuile/Docker-Image.git#:Python/base/docker
      args:
        - IMAGE=${IMAGE}
    volumes:
      - ../src:/root/src/:ro
      - ../data:/root/data/:rw
      - ../bin:/root/bin/:rw
      - ../build:/root/build/:rw
    working_dir:  /root/src/
